{% set version = "1.5.0" %}

package:
  name: pynio
  version: {{ version }}

source:
  url: https://github.com/NCAR/pynio/archive/{{ version }}.tar.gz
  sha256: e2bae6469541662835a7d13aa0185b73b13df56c2de6ce6f8e74cb17ba9a6143
  patches:
    - test_opendap2_url.patch

build:
  number: 3
  skip: True  # [win or py3k]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - gcc
    - numpy 1.7.*  # [py27]
    - g2clib 1.6.*
    - hdf4
    - hdf5 1.10.1
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal 2.2.*
    - libnetcdf 4.4.*
    - libuuid  # [osx]
    - proj4 4.9.3
    - util-linux  # [linux]
  run:
    - python
    - numpy >=1.7  # [py27]
    - g2clib 1.6.*
    - hdf4
    - hdf5 1.10.1
    - hdfeos2
    - hdfeos5
    - jasper
    - libgdal 2.2.*
    - libnetcdf 4.4.*
    - libgfortran
    - libuuid  # [osx]
    - proj4 4.9.3
    - util-linux  # [linux]

test:
  source_files:
    - test
    - ncarg
  requires:
    - nose
  imports:
    - Nio
  commands:
    - cd $SRC_DIR/test && nosetests  # [not win]
    - conda inspect linkages -p $PREFIX pynio  # [not win]
    - conda inspect objects -p $PREFIX pynio  # [osx]

about:
  home: http://www.pyngl.ucar.edu/Nio.shtml
  license: BSD 3-clause
  summary: 'PyNIO is a multi-format data I/O package with a NetCDF-style interface.'

extra:
  recipe-maintainers:
    - marylhaley
    - ocefpaf
    - jhamman
    - david-ian-brown
    - khallock
